# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:year/:month/:title/
highlight: pygments
excerpt_separator: "\n\n"
include: ['.htaccess']

# Setup
title:            "FuckBilibili"
# tagline:          Black Theme for Jekyll
description:      "这里集合了各种b站的黑科技和b站的系统缺陷以及漏洞的公开。我们的宗旨就是：干翻b站！≖‿≖✧"
url:              https://www.fuckbilibili.com
baseurl:          ""

# author:
#  name:           'Karlo Espiritu'
#  url:            https://twitter.com/karloespiritu

# github:
#   repo:           https://github.com/karloespiritu/blackdoc

# Exclude these files from your production _site
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME

gems:
- jekyll-redirect-from

miantags:
- fuckbilibili
- 哔哩哔哩
